Application/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Application.Pages
{
    public class AccountModel : PageModel
    {
        
        private ClientSocket client;
        public RideList rides;

        [TempData]
        public string Message {get; set;}

        public bool ShowMessage => !string.IsNullOrEmpty(Message);
        public void GenerateCreatedRides(){
            try{
                client = new ClientSocket();
                rides = JsonConvert.DeserializeObject<RideList>(client.GetCreatedRides(User.FindFirst(ClaimTypes.Email)?.Value));
            }
            catch(Exception e){
                Message="Something went wrong :( \n Please reload the page or try again later.";
            }
            
        }
        [HttpPost]
        public async Task<ActionResult> OnPostDeleteRideAsync(string Driver, string Seats, string Date, string Time,
        string DeparturePoint, string DestinationCity, string DestinationAddr, string Comment){
            Ride ride = new Ride();
            ride.Driver = Driver;
            ride.Seats = int.Parse(Seats);
            ride.Date = Date;
            ride.Time = Time;
            ride.DeparturePoint = DeparturePoint;
            ride.DestinationCity = DestinationCity;
            ride.DestinationAddr = DestinationAddr;
            ride.Comment = Comment;
            try{
                client = new ClientSocket();
                string asnwer = client.DeleteRide(ride);
                if(asnwer == "ok"){
                    Message= "Ride deleted succesfully";
                }
                else{
                    Message= "Something went wrong, please try again.";
                }
            }
            catch(Exception e){

            }
            return Redirect("Account");
        }

        [HttpPost]
        public async Task<IActionResult> OnPostLogoutAsync(){
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("Index");
        }
    }
}

Application/Pages/CreateRide.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Application.Pages
{
    public class CreateRideModel : PageModel
    {
        public int Hour { get; set;}
        public int Minute { get; set;}
        private ClientSocket client;
        [TempData]
        public string Message {get; set;}

        public bool ShowMessage => !string.IsNullOrEmpty(Message);

        [HttpPost]
        public IActionResult OnPostCreateRide
        (string seats, string start, string destC, string destA, string hour, string Minute, string date, string comment){
            
            if(string.IsNullOrEmpty(seats)||string.IsNullOrEmpty(start)||string.IsNullOrEmpty(destC)||string.IsNullOrEmpty(destA)||string.IsNullOrEmpty(date))
            {
                Message="Please fill in all value fields.";
                return Redirect("CreateRide");
            }
            int check;
            if(!Int32.TryParse(seats, out check)){
                Message = "Seats value is invalid.";
                return Redirect("Index");
            }
            string time = hour + ":" + Minute;
            string ride = User.FindFirst(ClaimTypes.Email)?.Value;
            ride += "," + seats;
            ride += "," + start;
            ride += "," + destC;
            ride += "," + destA;
            ride += "," + date;
            ride += "," + time;
            ride += "," + comment;

            client = new ClientSocket();
            var answer = client.CreateRide(ride);
                
            if(answer == "created"){
                return Redirect("Index");
            }
            else{
                Message="Something went wrong, please try again.";
                return Redirect("CreateRide");
            }
            
        }  
        [HttpPost]
        public async Task<IActionResult> OnPostLogoutAsync(){
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("Index");
        } 
    } 
}

Application/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Application.Pages
{
    public class IndexModel : PageModel
    {
        private ClientSocket client;

        public RideList rides;

        [TempData]
        public string Message {get; set;}

        public bool ShowMessage => !string.IsNullOrEmpty(Message);

        public void GenerateRides(){
            rides = new RideList();
            client = new ClientSocket();
            rides = JsonConvert.DeserializeObject<RideList>(client.GetRides());

        }

        public bool IsPassanger(Ride ride){
            bool answer = false;
            if(ride.passangers == null){
                return answer;
            }
            else{
                for(int i =0; i < ride.passangers.Count;i++){
                    if(ride.passangers[i] == GetEmail()){
                        answer = true;
                    }
                }
            }
            return answer;
        }
        public string GetEmail(){
            return User.FindFirst(ClaimTypes.Email)?.Value;
        }
        [HttpPost]  
        public async Task<IActionResult> OnPostLoginAsync(string email, string password){
            
            if(string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password)){
                Message = "Please fill in both email and password.";
                return Redirect("Index");
            }
            client = new ClientSocket();
            
            var login = client.Login(email,password);
            if(login.Equals("password")){
                
                Message ="Wrong password.";
                return Redirect("Index");
            }
            
            else if(login.Equals("notfound")){

                Message = "User has not been found. Are you sure the email is correct?";
                return Redirect("Index");
            }
            else{
                try{
                var identity = new ClaimsIdentity
                (new[]{ new Claim(ClaimTypes.Name, login)}, 
                CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Email, email));
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                }
                catch{
                    Message = "Something went wront :( \n Try again later.";
                    return Redirect("Index");
                } 
                return Redirect("Index");
            }   
        }
        
        [HttpPost]
        public async Task<IActionResult> OnPostLogoutAsync(){
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("Index");
        }

         [HttpPost]
        public async Task<ActionResult> OnPostJoinRideAsync(string Driver, string Seats, string Date, string Time,
        string DeparturePoint, string DestinationCity, string DestinationAddr, string Comment){
            if(Int16.Parse(Seats) == 0){
                Message = "Ride is already full.";
                return Redirect("Index");
            }
            Ride ride = new Ride();
            ride.Driver = Driver;
            ride.Seats = int.Parse(Seats);
            ride.Date = Date;
            ride.Time = Time;
            ride.DeparturePoint = DeparturePoint;
            ride.DestinationCity = DestinationCity;
            ride.DestinationAddr = DestinationAddr;
            ride.Comment = Comment;
            ride.passangers.Add(GetEmail());
            try{
                client = new ClientSocket();
                String answer = client.JoinRide(ride);
                if(answer == "joinedRide"){
                    Message= "Ride joined succsessfully.";
                }
                else if(answer == "alreadyJoined"){
                    Message= "You already had joined that ride.";
                }
                else{
                    Message = "Something went wrong. Please try again.";
                }
                
            }
            catch(Exception e){
                Message = "Something went wront, please try again.";
            }
            return Redirect("Index");
        }

        [HttpPost]
        public async Task<ActionResult> OnPostLeaveRideAsync(string Driver, string Seats, string Date, string Time,
        string DeparturePoint, string DestinationCity, string DestinationAddr, string Comment){
            Ride ride = new Ride();
            ride.Driver = Driver;
            ride.Seats = int.Parse(Seats);
            ride.Date = Date;
            ride.Time = Time;
            ride.DeparturePoint = DeparturePoint;
            ride.DestinationCity = DestinationCity;
            ride.DestinationAddr = DestinationAddr;
            ride.Comment = Comment;
            ride.passangers.Add(GetEmail());
            try{
                client = new ClientSocket();
                String answer = client.LeaveRide(ride);
                if(answer == "leftRide"){
                    Message= "Ride left succsessfully.";
                }
                else{
                    Message = "Something went wrong. Please try again.";
                }
                
            }
            catch(Exception e){
                Message = "Something went wront, please try again.";
            }
            return Redirect("Index");
        }


    }

    
}

Application/Pages/Register.cshtml.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class RegisterModel : PageModel{
    private ClientSocket client;
    [TempData]
    public string Message {get; set;}

    public bool ShowMessage => !string.IsNullOrEmpty(Message);
       
       
        [HttpPost]
        public async Task<IActionResult> OnPostRegisterAsync
        (string password, string confirm, string email, string phone, string name){
            
            if(string.IsNullOrEmpty(name)||string.IsNullOrEmpty(password)||string.IsNullOrEmpty(password)
            ||string.IsNullOrEmpty(password)||string.IsNullOrEmpty(password)||string.IsNullOrEmpty(password)){

                return Redirect("Register");

            }
            string answer ="";
            try{
                client = new ClientSocket();
                string user = password;
                user += "," + email;
                user += "," + phone;
                user += "," + name;
                answer = client.Register(user);
            }
            catch(Exception e){
                await OnPostRegisterAsync(password, confirm, email, phone, name);
            }
            if(!(password.Equals(confirm))){
                Message = "Passwords dont match";
                return Redirect("Register");
            }
            else if(answer.Equals("email")){
                Message = "A user with the given email already exists.";
                return Redirect("Register");

            }
            else if(answer.Equals("phone")){

                Message = "A user with the given mobile number already exists.";
                return Redirect("Register");

            }
            else if(answer.Equals("created")){
                await OnPostLoginAsync(email, password);
                return Redirect("Index");
            }
            else{
                Message = "Something went wrong, please try again.";
                return Redirect("Register");
            }

            
        }
        [HttpPost]  
        public async Task<IActionResult> OnPostLoginAsync(string email, string password){
            
            if(string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password)){
                Message = "Please fill in both email and password.";
                return Redirect("Register");
            }
            client = new ClientSocket();
            var login = client.Login(email,password);
            if(login.Equals("password")){
                
                Message ="Wrong password.";
                return Redirect("Register");
            }
            
            else if(login.Equals("notfound")){

                Message = "User has not been found. Are you sure the email is correct?";
                return Redirect("Register");
            }
            else{
                try{
                var identity = new ClaimsIdentity
                (new[]{ new Claim(ClaimTypes.Name, login)}, 
                CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Email, email));
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                }
                catch{
                    Message = "Something went wront :( \n Try again later.";
                    return Redirect("Register");
                } 
                return Redirect("Index");
            }   
             
        }
}

Application/Pages/Account.cshtml
@page
@model AccountModel

@if(!(User.Identity.IsAuthenticated)){
		Response.Redirect("Index");
    }
else{

    

<nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            
            <a class="navbar-brand" href="Index">Workable</a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="btn-succsess"><a href="CreateRide">Create a ride</a></li>  
                </ul>
                <ul class="nav navbar-nav navbar-right">
            
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle btn" data-toggle="dropdown"><b>@User.Identity.Name</b> <span class="caret"></span></a>
			            <ul id="login-dp" class="dropdown-menu">
				            <li>
                                <div class="row">
                                    <div class="form-group">
                                        <a href="Account"><button type="submit" class="btn btn-info btn-block appButtons">Account</button></a>
                                    </div>

                                    <div class="form-group">
                                        <form method="post" asp-page-handler="Logout">
                                            <button type="submit" class="btn btn-danger btn-block appButtons">Logout</button>
                                        </form>
                                    </div>
                                </div>
				            </li>
			            </ul>
                    </li>    
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

     @if(Model.ShowMessage){
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span></span></button>
            @Model.Message
        </div>
    }

<div>
        @{Model.GenerateCreatedRides();}
        <form method="post">
        <table class="table rides">
            <thead>
                <th>Driver</th>
                <th>Seats</th>
                <th>Date</th>
                <th>Time</th>
                <th>Departure point</th>
                <th>Destination city</th>
                <th>Destination address</th>
                <th>Additional information</th>
                <th></th>
            </thead>
            <tbody>
                @foreach(var ride in Model.rides.Rides){
                    <tr>
                        <td>@Html.DisplayFor(m => ride.Driver)</td>
                        <td>@Html.DisplayFor(m => ride.Seats)</td>
                        <td>@Html.DisplayFor(m => ride.Date)</td>
                        <td>@Html.DisplayFor(m => ride.Time)</td>
                        <td>@Html.DisplayFor(m => ride.DeparturePoint)</td>
                        <td>@Html.DisplayFor(m => ride.DestinationCity)</td>
                        <td>@Html.DisplayFor(m => ride.DestinationAddr)</td>
                        <td>@Html.DisplayFor(m => ride.Comment)</td>
                        <td><button asp-page-handler="DeleteRide" class="btn brn-xs btn-danger" asp-route-Driver="@ride.Driver"
                        asp-route-Seats ="@ride.Seats" asp-route-Date="@ride.Date" asp-route-Time="@ride.Time"
                        asp-route-DeparturePoint="@ride.DeparturePoint" asp-route-DestinationCity="@ride.DestinationCity"
                        asp-route-DestinationAddr="@ride.DestinationAddr" asp-route-Comment="@ride.Comment">
                        Delete</button></td>
                    </tr>
                }
            </tbody>
        </table>
        </form>
    </div>
}

Application/Pages/Index.cshtml
@page
@model IndexModel

    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            
            <a class="navbar-brand" href="Index">WeRide</a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @if(User.Identity.IsAuthenticated){
                        <li class="btn-succsess"><a href="CreateRide">Create a ride</a></li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                @if(!(@User.Identity.IsAuthenticated)){
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
			                <ul id="login-dp" class="dropdown-menu">
				                <li>
                                    <div class="row">
                                        <form method="post" asp-page-handler="Login">

                                            <div class="form-group">
                                                <input type="text" name="Email" class="form-control appButtons" placeholder="Email">
                                            </div>

                                            <div class="form-group">
                                                <input type="password" name="Password" class="form-control appButtons" placeholder="Password">
                                            </div>

                                            <div class="form-group">
                                                <button type="submit" class="btn btn-success btn-block appButtons">Login</button>
                                            </div>

                                        </form>

                                        <div class="form-group">
                                            <a href="Register"><button type="submit" class="btn btn-primary btn-block appButtons" >Register</button></a>
                                        </div>
                                    </div>     
				                </li>
			                </ul>
                        </li>  
                }
                else{
                    <li class="dropdown">
                            <a href="#" class="dropdown-toggle btn" data-toggle="dropdown"><b>@User.Identity.Name</b> <span class="caret"></span></a>
			                <ul id="login-dp" class="dropdown-menu">
				                <li>
                                    <div class="row">
                                         <div class="form-group">
                                            <a href="Account"><button type="submit" class="btn btn-info btn-block appButtons">Account</button></a>
                                        </div>

                                        <div class="form-group">
                                            <form method="post" asp-page-handler="Logout">
                                                <button type="submit" class="btn btn-danger btn-block appButtons">Logout</button>
                                            </form>
                                        </div>
                                    </div>
				                </li>
			                </ul>
                        </li>    
                }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    @if(Model.ShowMessage){
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            @Model.Message
        </div>
    }
    @{Model.GenerateRides();}
    <table class="table rides">
        <form method="post">
            <thead>
                <th>Driver</th>
                <th>Seats</th>
                <th>Date</th>
                <th>Time</th>
                <th>Departure point</th>
                <th>Destination city</th>
                <th>Destination address</th>
                <th>Additional information</th>
                <th></th>
            </thead>
            <tbody>
                    @foreach(var ride in Model.rides.Rides){
                    if(ride.Seats > 0){
                        <tr>
                            <td>@Html.DisplayFor(m => ride.Driver)</td>
                            <td>@Html.DisplayFor(m => ride.Seats)</td>
                            <td>@Html.DisplayFor(m => ride.Date)</td>
                            <td>@Html.DisplayFor(m => ride.Time)</td>
                            <td>@Html.DisplayFor(m => ride.DeparturePoint)</td>
                            <td>@Html.DisplayFor(m => ride.DestinationCity)</td>
                            <td>@Html.DisplayFor(m => ride.DestinationAddr)</td>
                            <td>@Html.DisplayFor(m => ride.Comment)</td>
                            @{if(User.Identity.IsAuthenticated && !(ride.Driver == Model.GetEmail()) && !(Model.IsPassanger(ride))){
                                <td><button asp-page-handler="JoinRide" class="btn brn-xs btn-info" asp-route-Driver="@ride.Driver"
                                asp-route-Seats ="@ride.Seats" asp-route-Date="@ride.Date" asp-route-Time="@ride.Time"
                                asp-route-DeparturePoint="@ride.DeparturePoint" asp-route-DestinationCity="@ride.DestinationCity"
                                asp-route-DestinationAddr="@ride.DestinationAddr" asp-route-Comment="@ride.Comment">
                                Join ride</button></td>
                            }
                            else if(Model.IsPassanger(ride)){
                                <td><button asp-page-handler="LeaveRide" class="btn brn-xs btn-danger" asp-route-Driver="@ride.Driver"
                                asp-route-Seats ="@ride.Seats" asp-route-Date="@ride.Date" asp-route-Time="@ride.Time"
                                asp-route-DeparturePoint="@ride.DeparturePoint" asp-route-DestinationCity="@ride.DestinationCity"
                                asp-route-DestinationAddr="@ride.DestinationAddr" asp-route-Comment="@ride.Comment">
                                Leave ride</button></td>
                            }}     
                     
                        </tr>
                    }}                 
            </tbody>
        </form>
    </table>

Application/Pages/Register.cshtml
@page
@model RegisterModel
	@{if(User.Identity.IsAuthenticated){
		Response.Redirect("Index");
	}}
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="Index">WeRide</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
			            <ul id="login-dp" class="dropdown-menu">
				            <li>
                                <div class="row">
                                    <form method="post" asp-page-handler="Login">

                                        <div class="form-group">
                                            <input type="text" name="Email" class="form-control appButtons" placeholder="Email">
                                        </div>

                                        <div class="form-group">
                                            <input type="password" name="Password" class="form-control appButtons" placeholder="Password">
                                        </div>

                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success btn-block appButtons">Login</button>
                                        </div>

                                    </form>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-block appButtons" action="Register.cshtml">Register</button>
                                    </div>
                                </div>     
				            </li>
			            </ul>
                    </li>  
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

	@if(Model.ShowMessage){
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span></span></button>
            @Model.Message 
        </div>
    }
	 
	 <div class="container">
			<div class="row main">
				<div class="panel-heading">
	               <div class="panel-title text-center">
	               		<h1 class="title">ITS WEDNESDAY MY DUDES</h1>
	               		<hr />
	               	</div>
	            </div> 
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" asp-page-handler="Register">
						
						<div class="form-group">
							<label for="email" class="cols-sm-2 control-label">Your Email</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="password" class="cols-sm-2 control-label">Password</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									<input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									<input type="password" class="form-control" name="confirm" id="confirm"  placeholder="Confirm your Password"/>
								</div>
							</div>
						</div>

                        <div class="form-group">
							<label for="phone" class="cols-sm-2 control-label">Your phone number</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="phone" id="phone"  placeholder="Enter your phone number"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Your name</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="name" id="name"  placeholder="Enter your name"/>
								</div>
							</div>
						</div>

						<div class="form-group ">
							<button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>
						</div>
					</form>
				</div>
			</div>
		</div>